{
  "runOn": [
    {
      "minServerVersion": "4.3.1",
      "topology": [
        "replicaset",
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    }
  ],
  "tests": [
    {
      "description": "FindOneAndDelete succeeds with RetryableWriteError from server",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "findAndModify"
          ],
          "errorCode": 112,
          "errorLabels": [
            "RetryableWriteError"
          ]
        }
      },
      "operation": {
        "name": "findOneAndDelete",
        "arguments": {
          "filter": {
            "x": {
              "$gte": 11
            }
          },
          "sort": {
            "x": 1
          }
        }
      },
      "outcome": {
        "result": {
          "_id": 1,
          "x": 11
        },
        "collection": {
          "data": [
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      }
    },
    {
      "description": "FindOneAndDelete fails if server does not return RetryableWriteError",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "findAndModify"
          ],
          "errorCode": 11600,
          "errorLabels": []
        }
      },
      "operation": {
        "name": "findOneAndDelete",
        "arguments": {
          "filter": {
            "x": {
              "$gte": 11
            }
          },
          "sort": {
            "x": 1
          }
        }
      },
      "outcome": {
        "error": true,
        "result": {
          "errorLabelsOmit": [
            "RetryableWriteError"
          ]
        },
        "collection": {
          "data": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      }
    },
    {
      "description": "FindOneAndDelete succeeds after PrimarySteppedDown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "findAndModify"
          ],
          "errorCode": 189,
          "errorLabels": [
            "RetryableWriteError"
          ]
        }
      },
      "operation": {
        "name": "findOneAndDelete",
        "arguments": {
          "filter": {
            "x": {
              "$gte": 11
            }
          },
          "sort": {
            "x": 1
          }
        }
      },
      "outcome": {
        "result": {
          "_id": 1,
          "x": 11
        },
        "collection": {
          "data": [
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      }
    },
    {
      "description": "FindOneAndDelete succeeds after WriteConcernError ShutdownInProgress",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "findAndModify"
          ],
          "errorLabels": [
            "RetryableWriteError"
          ],
          "writeConcernError": {
            "code": 91,
            "errmsg": "Replication is being shut down"
          }
        }
      },
      "operation": {
        "name": "findOneAndDelete",
        "arguments": {
          "filter": {
            "x": {
              "$gte": 11
            }
          },
          "sort": {
            "x": 1
          }
        }
      },
      "outcome": {
        "result": {
          "_id": 1,
          "x": 11
        },
        "collection": {
          "data": [
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      }
    }
  ]
}
